package com.llamacrypt.service;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;

import static org.junit.jupiter.api.Assertions.*;

class EncryptionServiceTest {
    private EncryptionService service;

    @TempDir
    Path tempDir;

    @BeforeEach
    void setUp() {
        service = new EncryptionService();
    }

    @Test
    void encrypt_withPassword_shouldCreateLcryptFile() throws IOException {
        Path source = tempDir.resolve("test.txt");
        byte[] content = "Hello, World!".getBytes();
        Files.write(source, content);

        EncryptionResult result = service.encrypt(source, "password123".toCharArray());

        assertNotNull(result.getOutputPath());
        assertTrue(result.getOutputPath().endsWith(".lcrypt"));
        assertFalse(result.hasAutoGeneratedKey());
        assertTrue(Files.exists(Path.of(result.getOutputPath())));
    }

    @Test
    void encrypt_withPassword_shouldPreserveSourceFile() throws IOException {
        Path source = tempDir.resolve("test.txt");
        byte[] content = "Test content".getBytes();
        Files.write(source, content);

        service.encrypt(source, "password123".toCharArray());

        assertArrayEquals(content, Files.readAllBytes(source));
    }

    @Test
    void encrypt_withoutPassword_shouldCreateLcryptFile() throws IOException {
        Path source = tempDir.resolve("test.txt");
        byte[] content = "Hello, World!".getBytes();
        Files.write(source, content);

        EncryptionResult result = service.encryptWithoutPassword(source);

        assertNotNull(result.getOutputPath());
        assertTrue(result.getOutputPath().endsWith(".lcrypt"));
        assertTrue(result.hasAutoGeneratedKey());
        assertNotNull(result.getAutoGeneratedKey());
        assertEquals(43, result.getAutoGeneratedKey().length());
        assertTrue(Files.exists(Path.of(result.getOutputPath())));
    }

    @Test
    void encrypt_withoutPassword_shouldGenerateBase64Key() throws IOException {
        Path source = tempDir.resolve("test.txt");
        byte[] content = "Test".getBytes();
        Files.write(source, content);

        EncryptionResult result = service.encryptWithoutPassword(source);

        assertTrue(result.getAutoGeneratedKey().matches("[A-Za-z0-9_-]+"));
    }

    @Test
    void encrypt_shouldClearPasswordFromMemory() throws IOException {
        Path source = tempDir.resolve("test.txt");
        byte[] content = "Test".getBytes();
        Files.write(source, content);

        char[] password = "secret".toCharArray();
        EncryptionResult result = service.encrypt(source, password);

        assertNotNull(result.getOutputPath());
        assertEquals(0, password[0]);
    }

    @Test
    void encrypt_shouldClearDerivedKeyFromMemory() throws IOException {
        Path source = tempDir.resolve("test.txt");
        byte[] content = "Test".getBytes();
        Files.write(source, content);

        EncryptionResult result = service.encrypt(source, "password".toCharArray());

        assertNotNull(result.getOutputPath());
    }
}
