package com.llamacrypt.service;

public final class EncryptionResult {
    private final String outputPath;
    private final String autoGeneratedKey;

    private EncryptionResult(String outputPath, String autoGeneratedKey) {
        this.outputPath = outputPath;
        this.autoGeneratedKey = autoGeneratedKey;
    }

    public static EncryptionResult withKey(String outputPath, String autoGeneratedKey) {
        return new EncryptionResult(outputPath, autoGeneratedKey);
    }

    public static EncryptionResult withoutKey(String outputPath) {
        return new EncryptionResult(outputPath, null);
    }

    public String getOutputPath() {
        return outputPath;
    }

    public String getAutoGeneratedKey() {
        return autoGeneratedKey;
    }

    public boolean hasAutoGeneratedKey() {
        return autoGeneratedKey != null;
    }
}
