package com.llamacrypt;

import com.llamacrypt.cli.*;
import com.llamacrypt.service.*;

import java.nio.file.Path;
import java.nio.file.Paths;

public class Main {
    private final ArgumentParser argumentParser;
    private final ConsoleIO consoleIO;
    private final EncryptionService encryptionService;
    private final DecryptionService decryptionService;

    public Main() {
        this.argumentParser = new ArgumentParser();
        this.consoleIO = new ConsoleIO();
        this.encryptionService = new EncryptionService();
        this.decryptionService = new DecryptionService();
    }

    public static void main(String[] args) {
        Main main = new Main();
        int exitCode = main.run(args);
        System.exit(exitCode);
    }

    public int run(String[] args) {
        try {
            ParsedArgs parsedArgs = argumentParser.parse(args);
            return execute(parsedArgs);
        } catch (InvalidArgumentException e) {
            consoleIO.printError(e.getMessage());
            printUsage();
            return 1;
        } catch (ServiceException e) {
            consoleIO.printError(e.getMessage());
            return 1;
        } catch (Exception e) {
            consoleIO.printError("An unexpected error occurred");
            return 1;
        }
    }

    private int execute(ParsedArgs args) {
        Path sourceFile = args.getSourceFile();

        if (!sourceFile.toFile().exists()) {
            consoleIO.printError("File not found: " + sourceFile);
            return 1;
        }

        try {
            switch (args.getMode()) {
                case ENCRYPT:
                    return encrypt(args);
                case ENCRYPT_KEY:
                    return encryptWithKey(args);
                case DECRYPT:
                    return decrypt(args);
                default:
                    consoleIO.printError("Unknown operation mode");
                    return 1;
            }
        } catch (ServiceException e) {
            consoleIO.printError(e.getMessage());
            return 1;
        }
    }

    private int encrypt(ParsedArgs args) {
        EncryptionResult result = encryptionService.encrypt(args.getSourceFile(), args.getPassword());
        consoleIO.printSuccess("File encrypted: " + result.getOutputPath());
        return 0;
    }

    private int encryptWithKey(ParsedArgs args) {
        EncryptionResult result = encryptionService.encryptWithoutPassword(args.getSourceFile());
        consoleIO.printSuccess("File encrypted: " + result.getOutputPath());
        consoleIO.printKey(result.getAutoGeneratedKey());
        return 0;
    }

    private int decrypt(ParsedArgs args) {
        DecryptionResult result = decryptionService.decrypt(args.getSourceFile(), args.getPassword());
        consoleIO.printSuccess("File decrypted: " + result.getOutputPath());
        return 0;
    }

    private void printUsage() {
        consoleIO.printInfo("Usage: lcrypt <command> <filename> [password]");
        consoleIO.printInfo("");
        consoleIO.printInfo("Commands:");
        consoleIO.printInfo("  encrypt     Encrypt a file with a password");
        consoleIO.printInfo("  encrypt-key Encrypt a file with auto-generated key");
        consoleIO.printInfo("  decrypt     Decrypt an encrypted file");
        consoleIO.printInfo("");
        consoleIO.printInfo("Examples:");
        consoleIO.printInfo("  lcrypt encrypt myfile.txt mypassword");
        consoleIO.printInfo("  lcrypt encrypt-key myfile.txt");
        consoleIO.printInfo("  lcrypt decrypt myfile.lcrypt mypassword");
    }
}
